import os
import numpy as np
import pandas as pd

from src.embedding.embedding import prepare_embedding

from src.data_parsing.parse_to_CFG import parse_java_to_cfg
from src.data_parsing.parse_to_DDG import parse_cfg_to_ddg
from src.embedding.graph_embedding_node2vec import generate_semantic_embeddings


def load_labels_from_csv(csv_path):
    """ Charge the csv file and create a mapping from Java file names to their corresponding bug labels (0 or 1) """
    df = pd.read_csv(csv_path)
    labels = {}
    for _, row in df.iterrows():
        class_name = row["name.1"]
        file_name = class_name.split(".")[-1] + ".java"
        if int(row["bug"]) > 0:
            bug_label = 1
        else:
            bug_label = 0
        labels[file_name] = bug_label
    return labels


def prepare_dual_dataset(dataset_root, labels_dict, w2v_model):
    """
        Extracts both AST and Semantic matrices for each Java file in the dataset.
            - AST Matrix: Prepared using the `prepare_embedding` function which utilizes the Word2Vec model.
            - Semantic Matrix: Generated by parsing the Java code into CFG and DDG, then applying Node2Vec to get a unified semantic embedding.
            
            The function ensures that both matrices are extracted for the same file before adding them to the dataset. 
            If either extraction fails, the file is skipped entirely to maintain alignment between X_ast, X_semantic, and y.
            
            This approach guarantees that X_ast[i] and X_semantic[i] always correspond to the same Java file, which is crucial for training the DH-CNN model effectively.
    """
    X_ast = []
    X_semantic = []
    y = []
    
    print("Extraction des matrices AST et Sémantiques en cours (cela peut prendre du temps)...")
    
    for root, _, files in os.walk(dataset_root):
        for file in files:
            if not file.endswith(".java"):
                continue
                
            full_path = os.path.join(root, file)
            if file not in labels_dict:
                continue
                
            with open(full_path, "r", encoding="utf-8", errors="ignore") as f:
                code = f.read()
                
            try:
                # AST
                ast_matrix = prepare_embedding(code, w2v_model)
                
                # CFG and DDG
                cfg = parse_java_to_cfg(code)
                ddg = parse_cfg_to_ddg(cfg)
                _, _, semantic_matrix = generate_semantic_embeddings(cfg, ddg)
                
                X_ast.append(ast_matrix)
                X_semantic.append(semantic_matrix)
                y.append(labels_dict[file])
                
            except Exception as e:
                print(f"  Skipped {file} due to error: {e}")
                
    return np.array(X_ast), np.array(X_semantic), np.array(y)