import os
import numpy as np
import pandas as pd

from src.embedding.embedding import prepare_syntax_embedding
from src.utils.config import Config
from src.data_parsing.parse_to_CFG import parse_java_to_cfg
from src.data_parsing.parse_to_DDG import parse_cfg_to_ddg
from src.data_parsing.parse_to_DFG import parse_cfg_to_dfg
from src.embedding.graph_embedding_node2vec import generate_semantic_embeddings


def load_labels_from_csv(csv_path):
    """ Charge the csv file and create a mapping from Java file names to their corresponding bug labels (0 or 1) """
    df = pd.read_csv(csv_path)
    labels = {}

    name_col = None
    possible_name_columns = ["name.1", "name", "filename", "class", "ClassName"]
    for col in possible_name_columns:
        if col in df.columns:
            name_col = col
            break
            
    if name_col is None:
        raise ValueError(f"Impossible to find name column in {csv_path}. Available columns: {df.columns.tolist()}")
    
    bug_col = "bug" if "bug" in df.columns else "bugs"

    for _, row in df.iterrows():
        class_name = row.get(name_col)

        if pd.isna(class_name):
            continue

        file_name = str(class_name).split(".")[-1] + ".java"

        bug_val = row.get(bug_col, 0)
        if pd.isna(bug_val):
            bug_val = 0

        if int(bug_val) > 0:
            bug_label = 1
        else:
            bug_label = 0
        labels[file_name] = bug_label
    return labels


def prepare_dual_dataset(dataset_root, labels_dict, model_or_tokenizer):
    """
        Extracts both Syntax (AST) and Semantic matrices for each Java file in the dataset.
            - AST Matrix : Supports switching between Word2Vec (baseline) and CodeBERT (Transformer) based on Config.SYNTAX_MODE.
            - Semantic Matrix: Generated by parsing the Java code into CFG, DDG and DFG, then applying Node2Vec to get a unified semantic embedding.
            The function ensures that both matrices are extracted for the same file before adding them to the dataset. 
            If either extraction fails, the file is skipped entirely to maintain alignment between the matrix
            
    """
    X_syn_1 = []
    X_syn_2 = []
    X_semantic = []
    y = []
    
    print(f"Extracting AST and Semantic matrices (Mode: {Config.SYNTAX_MODE.upper()})...")
    
    for root, _, files in os.walk(dataset_root):
        for file in files:
            if not file.endswith(".java"):
                continue
                
            full_path = os.path.join(root, file)
            if file not in labels_dict:
                continue
                
            with open(full_path, "r", encoding="utf-8", errors="ignore") as f:
                code = f.read()
                
            try:
                # Syntax Extraction (Dynamic Switch)
                syntax_out1, syntax_out2 = prepare_syntax_embedding(code, model_or_tokenizer)
                
                # Semantic Extraction
                try:
                    cfg = parse_java_to_cfg(code)
                    ddg = parse_cfg_to_ddg(cfg)
                    dfg = parse_cfg_to_dfg(cfg)
                    _, _, _, semantic_matrix = generate_semantic_embeddings(cfg, ddg, dfg)
                
                except Exception as e:
                    print(f" Empty matrix for {file}: {e}")
                    semantic_matrix=np.zeros((Config.MAX_TOKENS, Config.EMBEDDING_DIM))
                
                X_syn_1.append(syntax_out1)
                if Config.SYNTAX_MODE == "codebert":
                    X_syn_2.append(syntax_out2)
                    
                X_semantic.append(semantic_matrix)
                y.append(labels_dict[file])
                
            except Exception as e:
                print(f"  Skipped {file} due to AST error: {e}")
                
    if Config.SYNTAX_MODE == "codebert":
        return np.array(X_syn_1), np.array(X_syn_2), np.array(X_semantic), np.array(y)
    return np.array(X_syn_1), None, np.array(X_semantic), np.array(y)